/**
 * Application-level error codes and their corresponding HTTP status codes.
 * These are the canonical error identifiers used in API error responses.
 */

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  CUSTOMER_IN_USE: 'CUSTOMER_IN_USE',
  USER_IN_USE: 'USER_IN_USE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

export const HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  INVALID_CREDENTIALS: 401,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  DUPLICATE_REPORT: 409,
  EMAIL_ALREADY_EXISTS: 409,
  CUSTOMER_IN_USE: 409,
  USER_IN_USE: 409,
  INTERNAL_SERVER_ERROR: 500,
}
